#!/bin/sh

< `dirname $0`/src/residual_stroke_count.c	\
sed '
	5,1469!d
	s/[^0-9]//g
' | awk '
	BEGIN { g = 0; p = 255 }
	{
		if ($1 < p) {
			p = $1;
		} else if (g < $1 - p) {
			g = $1 - p;
			gl = NR;
		}
		p = $1;
	}
	END { print g, gl }
'
