#!/bin/bash

set -e

prev=0000
awk -F\" '/{"/ {print NR, $2}' src/kanji_db.c |
while read lino ch
do
	echo -n "$lino	"
	src=/tmp/dump_rad_so/$ch
	smallest_matching=zzzz
	if [[ ! -f $src ]]; then
		echo skipping: $ch
		continue
	fi

	while read code
	do
		if [[ $code == $prev ]]; then
			smallest_matching=$code
			break
		fi
		if [[ $code > $prev && $code < $smallest_matching ]]; then
			smallest_matching=$code
		fi
	done <$src
	if [[ $smallest_matching == 'zzzz' ]]; then
		echo -n "err:	$ch - "
	else
		prev=$smallest_matching
		echo -n "ok:	$ch - "
	fi
	cat $src | sort -u | tr '\n' ' '
	echo
done
