#!/bin/bash

set -e

prev=0000
grep \{\" src/kanji_db.c |
	awk -F\" '{print $2}' |
while read ch
do
	src=/tmp/dump_rad_so/$ch
	if [[ ! -f $src ]]; then
		new_code=$prev
		echo skipping: $ch > /dev/stderr
	else
		new_code=$(cat $src)
	fi
	if [[ $new_code < $prev ]]; then
		echo err: $ch
	fi
	prev=$new_code
done
