#!/usr/bin/env bash

set -e

src=$HOME/Desktop/Unihan/Unihan_RadicalStrokeCounts.txt

dir=/tmp/dump_rad_so
rm -rf $dir
mkdir -p $dir

echo 2c09 >>$dir/屠
echo 4307 >>$dir/斎
echo 5609 >>$dir/蒸
echo 7207 >>$dir/萬
echo a500 >>$dir/采

grep 'U+....	kRSAdobe_Japan1_6' $src |
	sed 's/kRSAdobe_Japan1_6	//' |
	sed 's/^U+//' |
while read code keys
do
	ch=$(printf '\u'$code)
	for key in $keys; do
		echo $key |
			sed -E 's/.*[+]//' |
			awk -F. '{ if ($1 == "23") {$1 = "22"} printf "%02x%02x\n", $1, $3}' >> $dir/$ch
	done
	printf .
done

echo
