#!/usr/bin/env bash

set -e

src=$HOME/Desktop/Unihan/Unihan_RadicalStrokeCounts.txt

dir=/tmp/dump_rad_so
rm -rf $dir
mkdir -p $dir

echo 2c09 >>$dir/屠
echo 4307 >>$dir/斎
echo 5609 >>$dir/蒸
echo 7207 >>$dir/萬
echo a500 >>$dir/采
echo 8702 >>$dir/舎
echo 8709 >>$dir/舗

format_code () {
	awk -F. '
{
	# 一画の部首を全て同一の部首として見なす。
	if ($1 <= 6) {$1 = "1"}

	# 人と儿と入と八を同一の部首として見なす。
	if ($1 >= 9 && $1 <= 12) {$1 = "9"}

	# 匚と匸を同一の部首として見なす。
	if ($1 == "23") {$1 = "22"}

	# 日と曰を同一の部首と見なす。
	if ($1 == "73") {$1 = "72"}

	printf "%02x%02x\n", $1, $3;
}'
}

grep 'U+....	kRSAdobe_Japan1_6' $src |
	sed 's/kRSAdobe_Japan1_6	//' |
	sed 's/^U+//' |
while read code keys
do
	ch=$(printf '\u'$code)
	for key in $keys; do
		echo $key |
			sed -E 's/.*[+]//' |
			format_code >> $dir/$ch
	done
	printf .
done

echo
