#!/bin/bash

src/nusort last_rank_contained -s \
	人 \
	侵 \
	八 \
	力 \
	又 \
	囗 \
	夂 \
	宀 \
	尸 \
	幺 \
	心 \
	戸 \
	提 \
	日 \
	木 \
	業 \
	气 \
	減 \
	爪 \
	疋 \
	示 \
	立 \
	細 \
	羽 \
	艸 \
	角 \
	谷 \
	足 \
	途 \
	里 \
	隹 \
	風 \
	| tee key_desc_out

exit 0
