#!/bin/bash

if [[ -z $RANK_SORT ]]; then
	flags=-s
	tee="tee key_desc_out"
else
	flags=
	tee=cat
fi

src/nusort last_rank_contained $flags \
	会 \
	信 \
	刀 \
	勹 \
	合 \
	土 \
	女 \
	宿 \
	工 \
	弋 \
	心 \
	戸 \
	提 \
	日 \
	木 \
	業 \
	气 \
	減 \
	爪 \
	疋 \
	示 \
	立 \
	結 \
	羽 \
	艸 \
	角 \
	谷 \
	足 \
	通 \
	里 \
	隹 \
	風 \
	| $tee

exit 0
