#!/bin/bash

src/nusort last_rank_contained -s \
	人 \
	侵 \
	八 \
	力 \
	口 \
	囗 \
	夂 \
	宀 \
	尸 \
	幺 \
	心 \
	手 \
	提 \
	日 \
	木 \
	棄 \
	水 \
	液 \
	爪 \
	疋 \
	石 \
	穴 \
	糸 \
	缶 \
	艸 \
	言 \
	谷 \
	足 \
	途 \
	金 \
	隹 \
	風 \
	| tee key_desc_out

exit 0
