#!/bin/sh

d=`dirname $0`
wd=/tmp/`basename $0`.$$

mkdir -p $wd

export LC_ALL=C
tr '\t' '@' <$d/../kanji_db.c		\
| sed '/^@{"\([^"]*\)".*/!d; s//\1/'	\
| sort -u				>$wd/kjdb

sort -u $d/../../priorities/jpn.*		>$wd/allj
sort -u $d/../../priorities/cht.*		>$wd/allz
sort -u $wd/kjdb $wd/allj $wd/allz	>$wd/allk

comm -13 $wd/kjdb $wd/allk >$wd/missing

appenno () {
	sed 's/$/ '$1/ $2
}

withpri () {
	pre=$d/../../priorities/$1
	alf=$wd/all$2
	for i in 1 2 3 4; do
		test -e		$pre.$i	\
		&& appenno $i	$pre.$i
	done
	comm -23 $wd/allk $alf | appenno 0
}

withpri jpn j | sort -u >$wd/pnoj
withpri cht z | sort -u >$wd/pnoz

join -j 1 -t ' ' $wd/missing	$wd/pnoj |
join -j 1 -t ' ' /dev/stdin	$wd/pnoz | sed '
	s/\(.*\) \(.\) \(.\)/@{"\1", ?????, ?, \2, \3},/
' | tr @ '\t'
