#!/bin/sh

export LC_ALL=C

< `dirname $0`/../third_party/Unihan_RadicalStrokeCounts.txt \
tr '\t' @ \
| sed '
	/^#/d

	/kRSAdobe_Japan1_6/{
		s///
		s/\([CV]\)+[0-9]*+\([0-9]*\)[.][^.]*/\1\2/g
		bt
	}

	/kRSKangXi/{
		s//kx/
		s/kx[^0-9]*/Z/
		bt
	}

	d

:t
	s/[ @]\{1,\}/,/g
' | perl -pC -e '
	BEGIN {
		binmode(STDOUT, ":utf8")
	}
	sub radcon {
		my ($r) = @_;
		if ($r <= 6	) { $r = 1	;}
		if ($r == 22	) { $r = 23	;}
		if ($r == 35	) { $r = 34	;}
		if ($r == 73	) { $r = 72	;}
		if ($r >= 30	) { $r += 1	;}
		return $r;
	}
	/U\+([A-F0-9]{4,})/ or die "bad line: $_";
	$c = chr(hex($1));
	s//$c/;
	$_ =~ s{([CVZ])([0-9]+)[.]([0-9]+)}{
		$1 . sprintf(q[%02x%02x], radcon($2), $3)
	}eg;
' >/tmp/separ.$$

grep [CV]	/tmp/separ.$$ >/tmp/only.j.$$
grep Z		/tmp/separ.$$ >/tmp/only.z.$$

join -t, -a 1 -a 2 -1 1 -2 1 /tmp/only.*.$$ \
| sed 's/ /,/g; s/,/ /'
